require "bundler/capistrano" 
load 'deploy'
# Uncomment if you are using Rails' asset pipeline
    # load 'deploy/assets'
load 'config/deploy' # remove this line to skip loading any of the default tasks
set :asset_env, "#{asset_env} RAILS_RELATIVE_URL_ROOT=/bootstrap"