source 'https://rubygems.org'

gem 'rails', '3.2.13'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
    gem 'rspec'
    gem 'rspec-rails'
    gem 'autotest'
    gem 'autotest-standalone'
end

gem 'jquery-rails'
gem 'haml'
gem 'devise'
gem 'haml-rails', :group => :development
gem 'resque', :require => "resque/server"
gem 'resque-scheduler'
gem 'whenever', :require => false
group :test do
  gem "database_cleaner"
  gem 'resque_spec'
  gem "email_spec"
  gem 'factory_girl_rails', :require => false
  gem "shoulda-matchers"
end
# `rspec-rails` needs to be in the development group so that Rails generators work.
group :development, :test do
  gem "rspec-rails"
end

gem 'hw_cheker', '~> 1.3.41'
gem 'nokogiri'
# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
