source 'https://rubygems.org'

gem 'rails', '3.2.13'

# Heart of project
gem 'hw_checker', '~> 1.3.48'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby

  gem 'jquery-datatables-rails', github: 'rweng/jquery-datatables-rails'
  gem 'jquery-ui-rails'
  gem 'twitter-bootstrap-rails'
  gem 'less-rails'

  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'autotest'
  gem 'autotest-standalone'
end

group :test do
  gem 'simplecov', :require => false
  gem 'database_cleaner'
  gem 'resque_spec'
  gem 'email_spec'
  gem 'factory_girl_rails'
  gem 'shoulda-matchers'
end

gem 'jquery-rails'
gem "highcharts-rails"
# To use HAML instead of inconvenient ERB
gem 'haml-rails'

# To create authentication easier
gem 'devise'

# To create queue of jobs using redis server
gem 'resque', :require => "resque/server"
gem 'resque-scheduler'

# To generate cron's schedule automatically
gem 'whenever'

gem 'will_paginate'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
